version: "3.9"
services:
  data:
    build:
      context: ./data
      dockerfile: Dockerfile
    environment:
      SPOTIFY_CLIENT_ID:
      SPOTIFY_CLIENT_SECRET:
      MONGODB_DATABASE:
      MONGODB_USERNAME:
      MONGODB_PASSWORD:
      MONGODB_HOSTNAME:
    networks:
      - backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2.2
    restart: unless-stopped
    command: mongod --auth
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: spotify
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
